package:
  name: rjmc-surrogate-models
  version: "0.0.0"

source:
  path: ../..

build:
  number: 0

requirements:
  host:
    - python
    - setuptools

  run:
    - python

test:
  requires:
    - pytest
  imports:
    - rjmc-surrogate-models

about:
  home: add_url_here
  license: BSD-3-Clause License
